name: MAEC Docs
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

copyright: The MITRE Corporation
generate_documentation: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', "Rakefile", "LICENSE"]

current_version: 4.1

encoding: utf-8
